# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-16 15:58
from __future__ import unicode_literals

from django.db import migrations


def change_learners_course_run(apps, schema_editor):
    """
    There are two course runs for course-v1:TUMx+QPLS2x+2T2018 and
    one of them is excluded from the program. But user grades are
    associated with excluded course run. That's why in program record
    status of the course course-v1:TUMx+QPLS2x+2T2018 is not earned for
    the learners even though learners program is completed.
    PROD-1443

    Changing course run id in user grade would fix that issue.

    """
    UserGrade = apps.get_model('records', 'UserGrade')
    CourseRun = apps.get_model('catalog', 'CourseRun')

    courses = CourseRun.objects.filter(key='course-v1:TUMx+QPLS2x+2T2018')
    if courses:
        excluded_run = courses.filter(id=119)
        included_run = courses.filter(id=8112)

        if excluded_run and included_run:
            for learner in UserGrade.objects.filter(course_run_id=excluded_run.id):
                learner.course_run_id = included_run.id
                learner.saver()


def reverse_change_learners_course_run(apps, schema_editor):

    UserGrade = apps.get_model('records', 'UserGrade')
    CourseRun = apps.get_model('catalog', 'CourseRun')

    courses = CourseRun.objects.filter(key='course-v1:TUMx+QPLS2x+2T2018')
    if courses:
        excluded_run = courses.filter(id=119)
        included_run = courses.filter(id=8112)

        if excluded_run and included_run:
            for learner in UserGrade.objects.filter(course_run_id=included_run.id):
                learner.course_run_id = excluded_run.id
                learner.saver()


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0017_ProgramCertRecord_unique_constraint'),
    ]

    operations = [
        migrations.RunPython(change_learners_course_run, reverse_code=reverse_change_learners_course_run)
    ]
